#!/bin/bash

# Retrieve arguments
domain=$1

# Check domain/path availability
sudo yunohost app checkurl $domain -a proftpd
if [[ ! $? -eq 0 ]]; then
    exit 1
fi

# Install Proftpd 
sudo apt-get install proftpd-mod-ldap -y

# Copy files to the right place
final_path=/etc/proftpd
sudo cp ../conf/* $final_path/
sudo sed -i "s@YUNODOMAIN@$domain@g" $final_path/

# add iptables rules
#sudo yunohost firewall allow tcp 5000:5100 
