#!/bin/bash

# Retrieve arguments
domain=$1


# Check domain/path availability
sudo yunohost app checkurl $domain -a proftpd
if [[ ! $? -eq 0 ]]; then
    exit 1
fi

# Check password if settings
if [[ -z "$2" ]];then
    passwd=$2
    echo "www-data:$passwd" | chpasswd
fi

# Install Proftpd 
sudo DEBIAN_FRONTEND='noninteractive' apt-get install proftpd-mod-ldap -y

# Copy files to the right place
final_path=/etc/proftpd
sudo cp ../conf/* $final_path/
sudo sed -i "s@YUNODOMAIN@$domain@g" $final_path/proftpd.conf

# Add iptables rules
#sudo yunohost firewall allow tcp 5000:5100 

# Restart service
sudo service proftpd restart
